univariable.analysis = function(variable){
  string = deparse(substitute(variable))
  attach(clean.webforum)
  jpeg(filename = paste(string, " Histogram.jpeg", sep = ""))
  file.remove(paste(string, " univariable.txt", sep = ""))
  output = capture.output(summary(variable))
  cat(output, file=paste(string, " univariable.txt", sep = ""), sep="n")
  #value = log(variable)
  #hist(value, prob = TRUE, xlim = c(0, 6), main = "", xlab = paste("Log ", string, sep = ""))
  #x= seq(min(value),max(value), by = 0.01)
  #curve(dsnorm(x, mean = mean(value), sd = sd(value), xi = s), col = "red", lwd = 2, add = TRUE)
  hist(variable, prob = TRUE, main = "", xlab = string)
  dev.off()
  detach(clean.webforum)
}
univariable.analysis(Analytic)
univariable.analysis(Clout)
univariable.analysis(Authentic)
univariable.analysis(Tone)
